In [45]:
def factorial(n):
    # Algoritmo recursivo para calcular el factorial de un número
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

In [46]:
def serie_fibo(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    return serie_fibo(n - 1) + serie_fibo(n - 2)

In [56]:
def suma_fibo4(n):
    if n == 0:
        return 1
    return factorial(serie_fibo(n)) + suma_fibo4(n - 1)

In [64]:
suma_fibo4(7)

6227061251

In [55]:
while True:
    n = input('Ingrese el valor "n": ')
    print(f"{suma_fibo4(int(n))}")

1
2
3
5
11
131
40451


ValueError: invalid literal for int() with base 10: ''

In [4]:
factorial(0)

1

# Programacion Dinámica

In [1]:
import numpy as np

In [2]:
class Elemento:
    """Clase elemento"""

    def __init__(self, valor, peso):
        self.valor = valor
        self.peso = peso

In [3]:
ele_1 = Elemento(2, 3)
ele_2 = Elemento(2, 1)
ele_3 = Elemento(4, 3)
ele_4 = Elemento(5, 4)
ele_5 = Elemento(3, 2)

lista_elementos = [ele_1, ele_2, ele_3, ele_4, ele_5]

capacidad = 7

In [69]:
np.zeros(shape=(len(lista_elementos) + 1, capacidad + 1), dtype=np.int16)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [7]:
# Algoritmo

# inicializamos matriz en numpy
matrix = np.zeros(shape=(len(lista_elementos) + 1, capacidad + 1), dtype=np.int16)

# Recorremos matriz
for i in range(matrix.shape[0]):  # Iteramos elementos
    if i != 0:
        elemento_actual = lista_elementos[i - 1]  # Asignamos elemento a evaluar
    for j in range(matrix.shape[1]):  # Iteramos capacidades
        capacidad_actual = j
        # Secuencias de escape
        if i == 0:
            break
        if j == 0:
            continue

        # Comparación
        if elemento_actual.peso <= capacidad_actual:
            valor_encima = matrix[i - 1, j]  # Elemento superior
            valor_desfasado = matrix[i - 1, j - elemento_actual.peso]  # Valor desfasado
            nuevo_valor = (
                valor_desfasado + elemento_actual.valor
            )  # Calculo del posible nuevo mejor valor
            matrix[i, j] = max([valor_encima, nuevo_valor])  # Comparación
        else:
            matrix[i, j] = matrix[i - 1, j]  # Reemplazo con el mejor valor.

matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  2,  2,  2,  2],
       [ 0,  2,  2,  2,  4,  4,  4,  4],
       [ 0,  2,  2,  4,  6,  6,  6,  8],
       [ 0,  2,  2,  4,  6,  7,  7,  9],
       [ 0,  2,  3,  5,  6,  7,  9, 10]], dtype=int16)

In [22]:
# picking_items based on a matrix and an ElementList
curr_row, curr_column = matrix.shape[0] - 1, matrix.shape[1] - 1

included_elements = []
for element in lista_elementos[::-1]:
    if matrix[curr_row, curr_column] != matrix[curr_row - 1, curr_column]:
        included_elements.append(element)
        curr_column = curr_column - element.peso
    curr_row = curr_row - 1

In [25]:
total_peso = 0
total_valor = 0
for element in included_elements:
    total_peso += element.peso
    total_valor += element.valor
    print(element.peso, ", ", element.valor)
print(total_peso)
print(total_valor)

2 ,  3
4 ,  5
1 ,  2
7
10


In [20]:
lista_elementos

In [4]:
from algoritmos.programacion_dinamica.mochila import (
    calcular_matriz_mochila,
    calcular_elementos_incluidos,
    mostrar_resultados,
)

In [5]:
matriz = calcular_matriz_mochila(lista_elementos, capacidad)
matriz

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  2,  2,  2,  2],
       [ 0,  2,  2,  2,  4,  4,  4,  4],
       [ 0,  2,  2,  4,  6,  6,  6,  8],
       [ 0,  2,  2,  4,  6,  7,  7,  9],
       [ 0,  2,  3,  5,  6,  7,  9, 10]], dtype=int16)

In [6]:
elementos_incluidos = calcular_elementos_incluidos(lista_elementos, matriz)
elementos_incluidos

In [7]:
mostrar_resultados(elementos_incluidos)

Lista de elementos: 
Elem	Peso	Valor
1	2	3
2	4	5
3	1	2
Total Peso:  7
Total Valor:  10


# Floyd Algorithm

In [57]:
import numpy as np

In [39]:
class Node:
    def __init__(self, name: str):
        self.name = name
        self.aristas = {
            name: {"nodo": self, "costo": 0},
        }

    def agregar_arista(self, nodo: "Node", costo: int):
        if nodo.name == self.name:
            print("Ruta inválida")
        elif nodo.name in self.aristas.keys():
            self.aristas[nodo.name]["costo"] = costo
            print("Ruta actualizada")
        else:
            self.aristas[nodo.name] = {"nodo": nodo, "costo": costo}
            print("Ruta creada")

In [134]:
class Grafo:
    def __init__(self):
        self.nodos: list[Node] = []

    def agregar_nodo(self, name: str):
        if name in [nodo.name for nodo in self.nodos]:
            print(f"El nodo {name} ya existe.")
        else:
            self.nodos.append(Node(name))
            print(f"Nodo {name} agregado.")

    def agregar_arista(self, nodo_origen: str, nodo_destino: str, costo: int):
        nodos_dict = {nodo.name: nodo for nodo in self.nodos}
        if nodo_origen and nodo_destino in nodos_dict.keys():
            nodos_dict[nodo_origen].agregar_arista(nodos_dict[nodo_destino], costo)
        else:
            print("Nodo inexistente")

    def listar_rutas(self):
        """ejm. {'origen': 'a', 'destino': 'b', 'costo': 3}"""
        lista_rutas = []
        for nodo in self.nodos:
            # lista_rutas.extend([ {'destino': arista['nodo'], 'costo': arista['costo']} for arista in nodo.aristas])
            for nombre_arista, datos_arista in nodo.aristas.items():
                item = {
                    "origen": nodo.name,
                    "destino": nombre_arista,
                    "costo": datos_arista["costo"],
                }
                lista_rutas.append(item)
        return lista_rutas

In [ ]:
class FloydMatrix:
    def __init__(self, grafo: Grafo):
        self.grafo = grafo
        self.inicializar_matrix()

    def inicializar_matrix(self):
        """Inicializa la matriz"""
        a = len(self.grafo.nodos)
        self.cost_matrix = np.full((a, a), np.inf)
        self.route_matrix = np.full(shape=(a, a), fill_value="-", dtype=str)
        return self

    def solve_matrix(self):
        """Resuelve la matriz"""
        # Asignamos pesos iniciales
        for ruta in self.grafo.listar_rutas():
            row_name = ruta["origen"]
            col_name = ruta["destino"]
            row_idx, col_idx = self.translate_index(row_name, col_name)
            self.cost_matrix[row_idx, col_idx] = ruta["costo"]
            self.route_matrix[row_idx, col_idx] = ruta["origen"]

        # Iteramos
        # for node in self.grafo.nodos:
        #     # Vamos a tomar un nodo pivote y evaluar la matriz resultante
        #     pivot = node.name
        #     pivoted_nodes = [node.name for node in self.grafo.nodos if node.name != pivot]

        #     for piv_node_row in pivoted_nodes:
        #         for piv_node_col in pivoted_nodes:
        #             if piv_node_row == piv_node_col:
        #                 continue
        #             curr_value = self.get_matrix_element(piv_node_row, piv_node_col, 'cost')
        #             candidate_cost = self.get_matrix_element(piv_node_row, pivot, 'cost') + self.get_matrix_element(pivot, piv_node_col, 'cost')

        #             if candidate_cost < curr_value:
        #                 self.set_matrix_element(piv_node_row, piv_node_col, candidate_cost, 'cost')
        #                 self.set_matrix_element(piv_node_row, piv_node_col, pivot, 'route')

    def translate_index(self, row_node: str, column_node: str):
        """Utilidad para traducir índices de la matriz"""
        mapping = {nodo.name: index for index, nodo in enumerate(self.grafo.nodos)}
        return (mapping[row_node], mapping[column_node])

    def get_matrix_element(self, row_node: str, column_node: str, matrix: str):
        row_idx, col_idx = self.translate_index(row_node, column_node)
        if matrix == "cost":
            return self.cost_matrix[row_idx, col_idx]
        elif matrix == "route":
            return self.route_matrix[row_idx, col_idx]

    def set_matrix_element(self, value, row_node: str, column_node: str, matrix: str):
        row_idx, col_idx = self.translate_index(row_node, column_node)
        if matrix == "cost":
            self.cost_matrix[row_idx, col_idx] = value
        elif matrix == "route":
            self.route_matrix[row_idx, col_idx] = value

In [176]:
grafo = Grafo()
grafo.agregar_nodo("a")
grafo.agregar_nodo("b")
grafo.agregar_nodo("c")
grafo.agregar_nodo("d")
grafo.agregar_arista("a", "b", 2)
grafo.agregar_arista("a", "d", 3)
grafo.agregar_arista("b", "a", 3)
grafo.agregar_arista("b", "c", 2)
grafo.agregar_arista("c", "d", 4)
grafo.agregar_arista("d", "a", -2)
grafo.agregar_arista("d", "b", 6)

Nodo a agregado.
Nodo b agregado.
Nodo c agregado.
Nodo d agregado.
Ruta creada
Ruta creada
Ruta creada
Ruta creada
Ruta creada
Ruta creada
Ruta creada


In [177]:
grafo.listar_rutas()

[{'origen': 'a', 'destino': 'a', 'costo': 0},
 {'origen': 'a', 'destino': 'b', 'costo': 2},
 {'origen': 'a', 'destino': 'd', 'costo': 3},
 {'origen': 'b', 'destino': 'b', 'costo': 0},
 {'origen': 'b', 'destino': 'a', 'costo': 3},
 {'origen': 'b', 'destino': 'c', 'costo': 2},
 {'origen': 'c', 'destino': 'c', 'costo': 0},
 {'origen': 'c', 'destino': 'd', 'costo': 4},
 {'origen': 'd', 'destino': 'd', 'costo': 0},
 {'origen': 'd', 'destino': 'a', 'costo': -2},
 {'origen': 'd', 'destino': 'b', 'costo': 6}]

In [180]:
floyd = FloydMatrix(grafo)
floyd.route_matrix

array([['-', '-', '-', '-'],
       ['-', '-', '-', '-'],
       ['-', '-', '-', '-'],
       ['-', '-', '-', '-']], dtype='<U1')

In [179]:
floyd.solve_matrix()
floyd.route_matrix

KeyError: np.float64(6.0)

In [ ]:
# inicializamos matriz con valores infinitos
a = len(grafo.nodos)
np.full((a, a), np.inf)


def translate_index(row: str, colum: str):
    """Translate index like ('a','b') to (1, 2)"""
    [{} for index, node_name in enumerate()]

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])